# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlopstestv1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_cde675dc469444c586104c52d18b532c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4cd549d166e845a0aa77b94a6c8b5998 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cde675dc469444c586104c52d18b532c }}/python:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlopstestv1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f3d4b66f8724ab8842ffbf071bfeefd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cde675dc469444c586104c52d18b532c }}/python:${{ github.sha }}'